apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: prometheus-blackbox-exporter.rules-rules
  namespace: monitoring
spec:
  groups:
    - name: blackbox-exporter.rules
      rules:
        - alert: BlackboxProbeFailed
          annotations:
            dashboard_url: https://grafana.com/d/blackbox-exporter-j4da/blackbox-exporter?instance={{ $labels.instance }}
            description: The probe failed for the instance {{ $labels.instance }}.
            summary: Probe has failed for the past minute.
          expr: |
            probe_success{} == 0
          for: 1m
          labels:
            severity: critical
        - alert: BlackboxLowUptime30d
          annotations:
            dashboard_url: https://grafana.com/d/blackbox-exporter-j4da/blackbox-exporter?instance={{ $labels.instance }}
            description: The probe has a lower uptime than 99.9% the last 30 days for the instance {{ $labels.instance }}.
            summary: Probe uptime is lower than 99.9% for the last 30 days.
          expr: |
            avg_over_time(probe_success{}[30d]) * 100 < 99.900000000000006
          labels:
            severity: info
        - alert: BlackboxSslCertificateWillExpireSoon
          annotations:
            dashboard_url: https://grafana.com/d/blackbox-exporter-j4da/blackbox-exporter?instance={{ $labels.instance }}
            description: The SSL certificate of the instance {{ $labels.instance }} is expiring within 3 weeks.
            summary: SSL certificate will expire soon.
          expr: |
            probe_ssl_earliest_cert_expiry{} - time() < 21 * 24 * 3600
          labels:
            severity: warning
